@startuml

!include ../include/default.iuml
!include ../include/activity.iuml
!include ../include/agent.iuml
!include ../include/entity.iuml
!include ../include/corporate-actions_announcement.iuml
!include ../include/corporate-actions_company.iuml
!include ../include/corporate-actions_shareholding.iuml
!include ../include/corporate-actions_transfer_agent.iuml

Company <|-down- agent
TransferAgent <|-down- agent
Announcement <|-down- entity
Shareholding <|-down- entity
ShareholdingUpdated <|-down- activity

Company -> TransferAgent : actedOnBehalfOf
TransferAgent -> Company : actedOnBehalfOf
Company -up-> ShareholdingUpdated : wasAssociatedWith
note on link: Role: Issuer
TransferAgent -> ShareholdingUpdated : wasAssociatedWith
note on link: Role: Registrar
Shareholding -> ShareholdingUpdated : wasGeneratedBy
ShareholdingUpdated -> Shareholding : used
Shareholding -> Shareholding : wasRevisionOf
ShareholdingUpdated -> Announcement : used
Shareholding <-[hidden]- Announcement

@enduml
