@startuml

!include ../include/default.iuml
!include ../include/activity.iuml
!include ../include/agent.iuml
!include ../include/entity.iuml
!include ../include/manufacturing_contractor.iuml
!include ../include/manufacturing_item.iuml
!include ../include/manufacturing_item_manufactured.iuml

Contractor <|-- Agent
Item <|-- Entity
ItemManufactured <|-- Activity

Contractor -> ItemManufactured : wasAssociatedWith
note on link: Role: Manufacturer
Item -up-> ItemManufactured : wasGeneratedBy
ItemManufactured -down-> Item : generated*
ItemCertified -> Item : used

@enduml
