@startuml

left to right direction

class Contractor
Contractor : Location: String

class Item
Item : PartID: String

class Certificate
Certificate : CertID: String

class ItemCertified

class Agent
Agent : id: String
Agent : externalId: String

class Entity
Entity : id: String
Entity : externalId: String

class Activity
Activity : id: String
Activity : externalId: String
Activity : startedAtTime: String
Activity : endedAtTime: String

Contractor --> ItemCertified : wasAssociatedWith
note on link: Role=Certifier

Certificate --> ItemCertified : wasGeneratedBy
ItemCertified --> Certificate : generated*

ItemCertified --> Item : used

Agent --|> Contractor
Entity --|> Certificate
Entity --|> Item
Activity --|> ItemCertified

@enduml
