@startuml

!include ../include/default.iuml
!include ../include/activity.iuml
!include ../include/agent.iuml
!include ../include/entity.iuml
!include ../include/manufacturing_certificate.iuml
!include ../include/manufacturing_contractor.iuml
!include ../include/manufacturing_item.iuml

Contractor <|-- Agent
Certificate <|-- Entity
Item <|-- Entity
ItemCertified <|-- Activity

Contractor -> ItemCertified : wasAssociatedWith
note on link: Role: Certifier
Certificate -right-> ItemCertified : wasGeneratedBy
ItemCertified -left-> Certificate : generated*
ItemCertified -> Item : used

@enduml
