@startuml

!include ../include/default.iuml
!include ../include/activity.iuml
!include ../include/agent.iuml
!include ../include/entity.iuml
!include ../include/artwork.iuml
!include ../include/artwork_details.iuml
!include ../include/artist.iuml
!include ../include/collector.iuml
!include ../include/created.iuml
!include ../include/exhibited.iuml
!include ../include/sold.iuml

Artwork <|-down- entity
ArtworkDetails <|-down- entity
Collector <|-down- agent
Artist <|-down- agent
Exhibited <|-down- activity
Created <|-down- activity
Sold <|-down- activity

@enduml
