@startuml

left to right direction

!include ../include/default.iuml

!include ../include/activity.iuml
!include ../include/agent.iuml
!include ../include/entity.iuml

!include ../include/time-recording_Person.iuml
!include ../include/time-recording_Work.iuml
!include ../include/time-recording_Project.iuml

' types

agent --|> Person
activity --|> Work
entity --|> Project

' relations

Work --> Person : wasAssociatedWith
note on link: Role: Worker

Work --> Project : used

@enduml
