@startuml

!include ../include/default.iuml

!include ../include/activity.iuml

!include ../include/time-recording_Person1.iuml
!include ../include/time-recording_Person2.iuml
!include ../include/time-recording_Work1.iuml
!include ../include/time-recording_Work2.iuml
!include ../include/time-recording_Timesheet.iuml
!include ../include/time-recording_Revision.iuml

' types

Activity --|> Revision

' relations

Work1 --> Person1 : wasAssociatedWith
note on link: Role: Worker

Work2 --> Person1 : wasAssociatedWith
note on link: Role: Worker

Timesheet --> Person1 : wasAssociatedWith
note on link: Role: Worker

Revision --> Person2 : wasAssociatedWith
note on link: Role: Administrator

Timesheet --> Work1 : wasInformedBy
Revision --> Work2 : wasInformedBy

Revision --> Timesheet : wasInformedBy

Person2 --> Person1 : actedOnBehalfOf
note on link: Role: Worker

@enduml
