@startuml

left to right direction

!include ../include/default.iuml

!include ../include/activity.iuml

!include ../include/time-recording_Person.iuml
!include ../include/time-recording_Timesheet.iuml
!include ../include/time-recording_View.iuml

' types

Activity --|> View

' relations

View --> Timesheet : wasInformedBy
View --> Person : wasAssociatedWith
note on link: Role: Supervisor

@enduml
