@startuml

!include ../include/default.iuml

!include ../include/time-recording_Person1.iuml
note left: staff-4366

!include ../include/time-recording_Person2.iuml
note bottom: staff-3621

!include ../include/time-recording_Person3.iuml
note right: staff-3150

!include ../include/time-recording_Timesheet.iuml
note left: ts-32205

!include ../include/time-recording_Revision.iuml
note top: rts-2130

!include ../include/time-recording_Submit.iuml
note top: submit-32470

!include ../include/time-recording_Approve.iuml
note top: approve-31305

' relations

Revision --> Timesheet : wasInformedBy
Submit --> Revision : wasInformedBy
Approve -> Submit : wasInformedBy

Timesheet --> Person1 : wasAssociatedWith
note on link: Role: Worker

Revision --> Person1 : wasAssociatedWith
note on link: Role: Worker

Submit --> Person1 : wasAssociatedWith
note on link: Role: Worker

Approve --> Person3 : wasAssociatedWith
note on link: Role: Administrator

Person3 --> Person2 : actedOnBehalfOf
note on link: Role: Supervisor

@enduml
