@startuml

!include ../include/default.iuml

!include ../include/time-recording_Person1.iuml
!include ../include/time-recording_Person2.iuml
!include ../include/time-recording_Timesheet.iuml
!include ../include/time-recording_Revision.iuml
!include ../include/time-recording_Submit.iuml

' relations

Revision --> Timesheet : wasInformedBy
Submit --> Revision : wasInformedBy

Timesheet --> Person1 : wasAssociatedWith
note on link: Role: Worker

Revision --> Person2 : wasAssociatedWith
note on link: Role: Administrator

Submit --> Person2 : wasAssociatedWith
note on link: Role: Administrator

Person2 --> Person1 : actedOnBehalfOf
note on link: Role: Worker

@enduml
