@startuml

left to right direction

!include ../include/default.iuml

!include ../include/activity.iuml

!include ../include/time-recording_Person1.iuml
!include ../include/time-recording_Person2.iuml
!include ../include/time-recording_Work.iuml
!include ../include/time-recording_Project.iuml
!include ../include/time-recording_Summary.iuml

' types

Activity --|> Summary

' relations

Summary --> Work : wasInformedBy

Summary --> Person2 : wasAssociatedWith
note on link: Role: Project Lead

Work --> Person1 : wasAssociatedWith
note on link: Role: Worker

Work --> Project : used

Summary --> Project : used

@enduml
