@startuml

!include ../include/default.iuml

!include ../include/activity.iuml

!include ../include/time-recording_Person1.iuml
!include ../include/time-recording_Person2.iuml
!include ../include/time-recording_Timesheet.iuml
!include ../include/time-recording_Submit.iuml

' types

activity --|> Submit
activity --|> Accept

' relations

Timesheet --> Person1 : wasAssociatedWith
note on link: Role: Worker

Submit --> Timesheet : wasInformedBy
Submit --> Person1 : wasAssociatedWith
note on link: Role: Worker

Accept --> Submit : wasInformedBy
Accept --> Person2 : wasAssociatedWith
note on link: Role: Supervisor

@enduml
