@startuml

left to right direction

!include ../include/default.iuml

!include ../include/activity.iuml

!include ../include/time-recording_Person.iuml
!include ../include/time-recording_Project.iuml
!include ../include/time-recording_Work.iuml
!include ../include/time-recording_Timesheet.iuml

' types

activity --|> Timesheet

' relations

Timesheet --> Work : wasInformedBy

Timesheet --> Person : wasAssociatedWith
note on link: Role: Worker

Work --> Person : wasAssociatedWith
note on link: Role: Worker

Work --> Project : used

@enduml
