@startuml

' core types

class Activity
Activity : id: String
Activity : externalId: String
Activity : startedAtTime: String
Activity : endedAtTime: String

' domain classes

class Person1 as "Person"
Person1 : Name: String

class Person2 as "Person"
Person2 : Name: String

class Work1 as "Work"
Work1 : Task: String

class Work2 as "Work"
Work2 : Task: String

class Timesheet

class Revision
Revision : Reason: String

' types

Activity --|> Revision

' relations

Work1 --> Person1 : wasAssociatedWith
note on link: Role=WORKER

Work2 --> Person1 : wasAssociatedWith
note on link: Role=WORKER

Timesheet --> Person1 : wasAssociatedWith
note on link: Role=WORKER

Revision --> Person2 : wasAssociatedWith
note on link: Role=ADMINISTRATOR

Timesheet --> Work1 : wasInformedBy
Revision --> Work2 : wasInformedBy

Revision --> Timesheet : wasInformedBy

Person2 --> Person1 : actedOnBehalfOf

@enduml
