#!/usr/bin/env bash

echo "Wait for stack"
HOST=domain
PORT=9982
TIMEOUT=300
echo "Wait for stack"
if ! wait-for-it -h $HOST -p $PORT -t $TIMEOUT; then
  echo "Timed out waiting for $HOST"
  exit 1
fi

echo "Subscribe to commits"
gq http://domain:9982/ws -q " \
subscription { \
  commitNotifications { \
    stage \
    delta \
    txId \
    error \
  } \
}" >subscription.out &

sleep 5

echo "Issue query"
gq http://domain:9982 -q " \
mutation{ \
        defineAgent( \
    externalId: \"test\",  \
    attributes: {}) { \
    txId \
  } \
}"

echo "Collecting commits"
sleep 30

cat subscription.out

grep COMMIT subscription.out
